# Copyright (c) 2024, 2025 Bart van de Lint, Uwe Fechner
# SPDX-License-Identifier: MIT

"""
    sim!(sam, set_values; dt, total_time, vsm_interval, prn)

Run a generic simulation for a given AWE model and a matrix of control inputs.

This is the core simulation function that steps through time, applies control inputs,
and logs the system state.

# Arguments
- `sam::SymbolicAWEModel`: Initialized AWE model.
- `set_values::Matrix{Float64}`: A matrix of external control torques [Nm] to be
  applied at each time step. The number of rows must equal the number of
  simulation steps, and the number of columns must equal the number of winches.

# Keywords
- `dt::Float64`: Time step [s]. Defaults to `1/sam.set.sample_freq`.
- `total_time::Float64`: Total simulation duration [s]. Defaults to 10.0.
- `vsm_interval::Int`: Interval for the value state machine updates. Defaults to 3.
- `prn::Bool`: If true, prints a performance summary upon completion. Defaults to true.

# Details
The `set_values` represent external control torques. Internally, the function
calculates the total torque for each winch by adding the external torque to the
torque generated by the existing tether force on the drum. This total torque is
then used as the set-point for the winch controller in the subsequent step.

# Returns
- `SysLog`: A log object containing the time-series data of the simulation.
"""
function sim!(
    sam::SymbolicAWEModel,
    set_values::Matrix{Float64};
    dt=1/sam.set.sample_freq,
    total_time=10.0,
    vsm_interval=3,
    prn=true
)
    steps = Int(round(total_time / dt))
    if size(set_values, 1) != steps
        error("The number of rows in set_values ($(size(set_values, 1))) must match the number of simulation steps ($steps).")
    end

    logger = Logger(length(sam.sys_struct.points), steps)
    sys_state = SysState(sam)

    if prn
        @info "Starting simulation"
    end
    step_time = 0.0
    vsm_time = 0.0
    integ_time = 0.0

    elapsed = @elapsed for step in 1:steps
        t = (step-1) * dt

        # Calculate internal set values based on current winch forces and external inputs
        internal_set_values = -sam.set.drum_radius .* [norm(winch.force) for winch in sam.sys_struct.winches]
        internal_set_values .+= set_values[step, :]

        try
            step_time += @elapsed next_step!(sam; set_values=internal_set_values, dt, vsm_interval=vsm_interval)
            integ_time += sam.t_step
            vsm_time += sam.t_vsm
            # Reset timers for the first half of the simulation to get a more stable performance measure
            if step < steps ÷ 2
                step_time, integ_time, vsm_time = 0.0, 0.0, 0.0
            end
        catch e
            if e isa AssertionError
                if prn
                    @warn "Crashed at t=$t"
                end
                break
            else
                rethrow(e)
            end
        end
        update_sys_state!(sys_state, sam)
        sys_state.time = t
        log!(logger, sys_state)
    end

    mkpath(get_data_path())
    save_log(logger, "tmp_run")
    lg = load_log("tmp_run")

    if prn
        lines = [
            "Performance Summary:",
            @sprintf("%-12s | %-12s | %-10s", "Component", "Speedup (×)", "Total Time"),
            "-------------|--------------|------------",
            @sprintf("%-12s | %12.2f | %10.2f", "Simulation", total_time / elapsed / 2, elapsed),
            @sprintf("%-12s | %12.2f | %10.2f", "Step",       total_time / step_time / 2, step_time),
            @sprintf("%-12s | %12.2f | %10.2f", "Integrator", total_time / integ_time / 2, integ_time),
            @sprintf("%-12s | %12.2f | %10.2f", "VSM",        total_time / vsm_time / 2, vsm_time)
        ]
        @info join(lines, "\n")
    end

    return lg
end


"""
    sim_oscillate!(sam; dt, total_time, steering_freq, steering_magnitude, vsm_interval, bias, prn)

Run a simulation with oscillating steering input on the given AWE model.

This function is a high-level wrapper around `sim!` that generates sinusoidal
control inputs to simulate figure-eight maneuvers or steering tests.

# Arguments
- `sam::SymbolicAWEModel`: Initialized AWE model.

# Keywords
- `dt::Float64`: Time step [s]. Defaults to `1/sam.set.sample_freq`.
- `total_time::Float64`: Simulation duration [s]. Defaults to 10.0.
- `steering_freq::Float64`: Steering oscillation frequency [Hz]. Defaults to 0.5.
- `steering_magnitude::Float64`: Steering torque amplitude [Nm]. This torque is
  applied positively to one steering winch and negatively to the other. Defaults to 10.0.
- `vsm_interval::Int`: Value state machine interval. Defaults to 3.
- `bias::Float64`: Phase bias [rad] for the steering cosine wave. Defaults to 0.13.
- `prn::Bool`: If true, prints progress and summary information. Defaults to false.

# Returns
- `SysLog`: A log object containing the time-series data of the simulation.
"""
function sim_oscillate!(
    sam::SymbolicAWEModel;
    dt=1/sam.set.sample_freq,
    total_time=10.0,
    steering_freq=0.5,
    steering_magnitude=10.0,
    vsm_interval=3,
    bias = 0.13,
    prn=false
)
    steps = Int(round(total_time / dt))
    num_winches = length(sam.sys_struct.winches)
    @assert num_winches == 3
    set_values = zeros(Float64, steps, num_winches)

    if prn
        @info "Generating oscillating steering commands..."
    end

    for step in 1:steps
        t = (step-1) * dt
        steering = steering_magnitude * cos(2π * steering_freq * t + bias)
        set_values[step, :] = [0.0, steering, -steering]
    end

    return sim!(sam, set_values; dt=dt, total_time=total_time, vsm_interval=vsm_interval, prn=prn)
end

"""
    sim_turn!(sam; dt, total_time, steering_time, steering_magnitude, vsm_interval, prn)

Run a simulation with a constant steering input for a specified duration.

This function is a wrapper around `sim!` that generates a step input for steering,
holds it for a duration of `steering_time`, and then returns to zero. It is useful
for analyzing the step response of the kite's turning behavior.

# Arguments
- `sam::SymbolicAWEModel`: Initialized AWE model.

# Keywords
- `dt::Float64`: Time step [s]. Defaults to `1/sam.set.sample_freq`.
- `total_time::Float64`: Total simulation duration [s]. Defaults to 10.0.
- `steering_time::Float64`: Duration of the constant steering input [s]. Defaults to 2.0.
- `steering_magnitude::Float64`: Steering torque amplitude [Nm]. Applied positively
  to one steering winch and negatively to the other. Defaults to 10.0.
- `vsm_interval::Int`: Value state machine interval. Defaults to 3.
- `prn::Bool`: If true, prints progress and summary information. Defaults to false.

# Returns
- `SysLog`: A log object containing the time-series data of the simulation.
"""
function sim_turn!(
    sam::SymbolicAWEModel;
    dt=1/sam.set.sample_freq,
    total_time=10.0,
    steering_time=2.0,
    steering_magnitude=10.0,
    vsm_interval=3,
    prn=false
)
    steps = Int(round(total_time / dt))
    steering_steps = Int(round(steering_time / dt))
    num_winches = length(sam.sys_struct.winches)
    @assert num_winches == 3
    set_values = zeros(Float64, steps, num_winches)

    if prn
        @info "Generating turn commands..."
    end

    for step in 1:steps
        if step <= steering_steps
            set_values[step, :] = [0.0, steering_magnitude, -steering_magnitude]
        else
            set_values[step, :] = zeros(num_winches)
        end
    end

    return sim!(sam, set_values; dt=dt, total_time=total_time, vsm_interval=vsm_interval, prn=prn)
end

