name: Update Default Manifest, Create xz files and PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update-and-pr:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest

    steps:
      - name: Install matplotlib
        run: sudo apt-get install -y python3-matplotlib
        shell: bash

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Use default manifest
        run: |
          if [ -f Manifest.toml.default ]; then cp Manifest.toml.default Manifest.toml; fi
        shell: bash

      - name: Set up Julia
        uses: julia-actions/install-juliaup@v2
        with:
          channel: 'release'

      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      - name: Build PyCall
        run: julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate(); Pkg.add("PyCall"); Pkg.build("PyCall")'
        shell: bash

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to new branch
        run: |
          BRANCH="update-manifest-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Run update script
        run: bin/update_default_manifest

      - name: Create xz files
        run: bin/create_xz_file

      - name: Commit changes
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update default manifest"
            git push origin $BRANCH
          else
            echo "No changes to commit."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH }}
          base: main
          title: "Update default manifest"
          body: "Automated update of default manifest."
